services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    image: node_app_image
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env

  react_app:
    container_name: react_app
    build: ./front-end
    image: react_app_image
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    image: nginx_app_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - react_app

volumes:
  pg:
  build_react:
